// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3zOl0ioW5cbExGORqXavXcRxzBycFlns',
    appId: '1:385675543410:web:0d7a8afb6e7fc5df8e53eb',
    messagingSenderId: '385675543410',
    projectId: 'hive-app-f3c2d',
    authDomain: 'hive-app-f3c2d.firebaseapp.com',
    storageBucket: 'hive-app-f3c2d.firebasestorage.app',
    measurementId: 'G-VFHV7Q118M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFMlM1AOWZzGNHS55bkTnRJrP13f9518M',
    appId: '1:385675543410:android:587ebd13f64a8ba48e53eb',
    messagingSenderId: '385675543410',
    projectId: 'hive-app-f3c2d',
    storageBucket: 'hive-app-f3c2d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3zOl0ioW5cbExGORqXavXcRxzBycFlns',
    appId: '1:385675543410:web:a8e4f8c29d2808dd8e53eb',
    messagingSenderId: '385675543410',
    projectId: 'hive-app-f3c2d',
    authDomain: 'hive-app-f3c2d.firebaseapp.com',
    storageBucket: 'hive-app-f3c2d.firebasestorage.app',
    measurementId: 'G-RM4BD717VF',
  );

}